spring.application.name=bankpro-banking-app
server.port=8080
server.address=0.0.0.0

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info
